apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
spec:
  project: default
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    path: 'charts/prometheus'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}
